runtime: nodejs8 # For Node.js 8, use runtime: nodejs8

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /
  static_dir: build
  secure: always
  redirect_http_response_code: 301